version: "3.7"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka0:
    image: 'bitnami/kafka:latest'
    ports:
      - '92092:9092'
      - '29094:29094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://kafka0:9092,LISTENER_ALICE://kafka0:29094
      - KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://never-gonna-give-you-up:29094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
    depends_on:
      - zookeeper

  consumer:
    image: 'pulish-data'
    build: 
      context: ./
      dockerfile: Dockerfile  
    ports:
      - '7000:7000'
    environment:
      kafka.bootstrapAddress: kafka0:29092
      bootstrap.servers: kafka0:29092 
    depends_on:
      - kafka0